### ISSUE TITLE
关于服务器的部署

### ISSUE THREAD

**Issue by zplzpl** [derekhe/crawler-book#1]
http://www.april1985.com/post/2020-05-13-k3s/
文中似乎没有提到一些依赖的部署，比如ES、Kibana、kafka、redis、pg是部署在哪？

**Comment by derekhe** [comment]
都部署在digitalocean的同一个区域的不同的node里面。是一个master node + n * worker ndoe这样的布局。

**Comment by zplzpl** [comment]
大概是什么样得配置？

**Comment by zplzpl** [comment]
我看完了你的书，书中，似乎也没有这块的描述。

**Comment by derekhe** [comment]
我目前的布局是
master node:
1 * 1C 1G k3s 主服务
worker node:
3 * 1C 1G  放置爬虫
1 * 2C 2G 放置ES、Kibana、Kafka、Redis、PG
1 * 1C 1G 放置监控相关的模块

其实k8s可以根据自己的需要和服务的载荷动态的分配到不同的worker node，我这样的区分主要是为了将爬虫单独放出来，减少和别的模块的干扰。

当然也可以在一个4C 8G的机器上，将所有的服务部署上去，也是可行的。

**Comment by zplzpl** [comment]
ES 2G ，是否需要做什么优化配置？或者是ES这边的请求和数量量不大？

**Comment by derekhe** [comment]
根据自身的服务器的负荷来。我这个配置只能是最低配置，因为小程序日活不高。
另外我开开了一些swap来作为内存，这也是一种投机取巧的方式。
