### ISSUE TITLE
乱码问题

### ISSUE THREAD

**Issue by jingzhoupanda** [derekhe/crawler-book#2]
请问下作者我已经购买了书籍，看书上第三章针对共享汽车以gofun为案例进行说明，我使用ios系统安装了gofun和evcard，为什么在charles上爬取gofun数据出现乱码，而evcard能正常读取？并且我看爬取evcard在Charles上得到的数据条目与gofun不一样，教程上的说明不能有效对应，请问您那是否还有专门针对evcard的教程呢？如果有我愿意购买，谢谢您。

**Comment by derekhe** [comment]
目前书出版已经比较久了，由于对方也在不断的修改，所以目前的源代码不能完全保证能够正确的执行。
gofun数据出现乱码很有可能是数据被加密等导致。
另外，gofun和evcard是不同的公司，API设计也不一样，历经一年也有不断地在更新，所以需要自己尝试研究下。
目前我没有针对更新的evcard提供更新。如果还有需要交流的可以联系微信号bcdata

**Comment by jingzhoupanda** [comment]
好的，谢谢您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hesicong"<notifications@github.com&gt;; 
发送时间: 2020年7月14日(星期二) 晚上8:42
收件人: "derekhe/crawler-book"<crawler-book@noreply.github.com&gt;; 
抄送: "李皓"<932341942@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [derekhe/crawler-book] 乱码问题 (#2)





 
目前书出版已经比较久了，由于对方也在不断的修改，所以目前的源代码不能完全保证能够正确的执行。
 gofun数据出现乱码很有可能是数据被加密等导致。
 另外，gofun和evcard是不同的公司，API设计也不一样，历经一年也有不断地在更新，所以需要自己尝试研究下。
 目前我没有针对更新的evcard提供更新。如果还有需要交流的可以联系微信号bcdata
